//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 09:36:49 AM CET 
//

package be.vdab.JAXBClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for KlantType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="KlantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Voornaam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Familienaam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Straat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Huisnr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gemeente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gebruikersnaam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Paswoord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KlantType", propOrder = { "voornaam", "familienaam", "straat",
		"huisnr", "postcode", "gemeente", "email", "gebruikersnaam", "paswoord" })
public class KlantType {

	public KlantType(String voornaam, String familienaam, String straat,
			String huisnr, String postcode, String gemeente,
			String gebruikersnaam, String paswoord, String email) {
		super();
		this.voornaam = voornaam;
		this.familienaam = familienaam;
		this.straat = straat;
		this.huisnr = huisnr;
		this.postcode = postcode;
		this.gemeente = gemeente;
		this.email = email;
		this.gebruikersnaam = gebruikersnaam;
		this.paswoord = paswoord;
	}

	@XmlElement(name = "Voornaam", required = true)
	protected String voornaam;
	@XmlElement(name = "Familienaam", required = true)
	protected String familienaam;
	@XmlElement(name = "Straat", required = true)
	protected String straat;
	@XmlElement(name = "Huisnr", required = true)
	protected String huisnr;
	@XmlElement(name = "Postcode", required = true)
	protected String postcode;
	@XmlElement(name = "Gemeente", required = true)
	protected String gemeente;
	@XmlElement(name = "Email", required = true)
	protected String email;
	@XmlElement(name = "Gebruikersnaam", required = true)
	protected String gebruikersnaam;
	@XmlElement(name = "Paswoord", required = true)
	protected String paswoord;

	/**
	 * Gets the value of the voornaam property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVoornaam() {
		return voornaam;
	}

	/**
	 * Sets the value of the voornaam property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVoornaam(String value) {
		this.voornaam = value;
	}

	/**
	 * Gets the value of the familienaam property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFamilienaam() {
		return familienaam;
	}

	/**
	 * Sets the value of the familienaam property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFamilienaam(String value) {
		this.familienaam = value;
	}

	/**
	 * Gets the value of the straat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStraat() {
		return straat;
	}

	/**
	 * Sets the value of the straat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStraat(String value) {
		this.straat = value;
	}

	/**
	 * Gets the value of the huisnr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHuisnr() {
		return huisnr;
	}

	/**
	 * Sets the value of the huisnr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHuisnr(String value) {
		this.huisnr = value;
	}

	/**
	 * Gets the value of the postcode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPostcode() {
		return postcode;
	}

	/**
	 * Sets the value of the postcode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPostcode(String value) {
		this.postcode = value;
	}

	/**
	 * Gets the value of the gemeente property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGemeente() {
		return gemeente;
	}

	/**
	 * Sets the value of the gemeente property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGemeente(String value) {
		this.gemeente = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value) {
		this.email = value;
	}

	/**
	 * Gets the value of the gebruikersnaam property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGebruikersnaam() {
		return gebruikersnaam;
	}

	/**
	 * Sets the value of the gebruikersnaam property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGebruikersnaam(String value) {
		this.gebruikersnaam = value;
	}

	/**
	 * Gets the value of the paswoord property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaswoord() {
		return paswoord;
	}

	/**
	 * Sets the value of the paswoord property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaswoord(String value) {
		this.paswoord = value;
	}

}
