//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 09:36:49 AM CET 
//


package be.vdab.JAXBClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Klant" type="{http://springcultuurhuis.stijnvansieleghem.cloudbees.net/schemas}KlantType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "klant"
})
@XmlRootElement(name = "NieuweKlantRequest")
public class NieuweKlantRequest {

	protected NieuweKlantRequest(){}
	
    public NieuweKlantRequest(KlantType klant) {
		super();
		this.klant = klant;
	}

	@XmlElement(name = "Klant", required = true)
    protected KlantType klant;

    /**
     * Gets the value of the klant property.
     * 
     * @return
     *     possible object is
     *     {@link KlantType }
     *     
     */
    public KlantType getKlant() {
        return klant;
    }

    /**
     * Sets the value of the klant property.
     * 
     * @param value
     *     allowed object is
     *     {@link KlantType }
     *     
     */
    public void setKlant(KlantType value) {
        this.klant = value;
    }

}
